CROSS_COMPILE=/home/java/basic/cross_compile/gcc-4.6.2-glibc-2.13-linaro-multilib-2011.12/fsl-linaro-toolchain/bin/arm-fsl-linux-gnueabi-
CC=${CROSS_COMPILE}gcc --static
key_gpio: key_gpio.o
clean:
	rm key_gpio key_gpio.o
