export ARCH=arm
export CROSS_COMPILE=/home/java/basic/cross_compile/gcc-4.6.2-glibc-2.13-linaro-multilib-2011.12/fsl-linaro-toolchain/bin/arm-fsl-linux-gnueabi-
CC=${CROSS_COMPILE}gcc --static
led: led.o
clean:
	rm led led.o
